spring.application.name=gymapp

spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres
spring.datasource.username=postgres.jmarblqgvyhfrsozooya
spring.datasource.password=f5j5nh4sPeeK8qCL!ghtTYU&/345..@FD
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.data-source-properties.prepareThreshold=0

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=D4_7N*5$8vtwQY459486_erfgrr666_6
app.jwt.expiration-ms=86400000

server.port=8080

app.crypto.key=qCL!ghtTYU&/345..

spring.config.activate.on-profile=local

webpush.vapid.public-key=BBWdKlkeKJYpw0jjQwv4tJ2WhlMJUM6OvRpijaoEn0LanD83uI5NM7eKJ3_7pQvQldbMMtntL2eBhJPDJo4O4UU
webpush.vapid.private-key=RMK9dMTqQF4edsQgGOVGB1q1QdJA8uX80juXtUIXgo4
webpush.vapid.subject=mailto: <caruso9307@hotmail.com>